### PR TITLE
fix: first line is empty

### LINKED ISSUE #22: [bug] 识别时，第一行文字总是空的
有个 logo 图片，中英文的，只把英文的识别出来了，但是 eSearch-OCR 把中英文都识别出来了，不过 gutenye-ocr 某些表现又比 eSearch-OCR 要好

我原以为是个别图片，发现不是个例

-----

例图：
这张图片，第一行丢失了 (box 目测正常，但是文字是空)
这张图片，第一行丢失了 (box 目测正常，但是文字是空)
这张图片，第一行丢失了 (box 目测正常，但是文字是空)

例图
```js
[
  {
    mean: 0,
    text: '',
    box: [ [ 20, 13 ], [ 926, 13 ], [ 926, 37 ], [ 20, 37 ] ]
  },
  {
    mean: 0.9640309434870015,
    text: "country's entrepreneurs shy away from launches",
    box: [ [ 18, 58 ], [ 676, 57 ], [ 676, 83 ], [ 18, 84 ] ]
  },
  {
    mean: 0.9646686973321773,
    text: 'Aggregate amounts inSbn Companies founded',
    box: [ [ 19, 141 ], [ 761, 141 ], [ 761, 162 ], [ 19, 164 ] ]
  },
  {
    mean: 0.9906626964608828,
    text: 'Dollar-denominated funds',
    box: [ [ 152, 214 ], [ 397, 215 ], [ 397, 236 ], [ 152, 235 ] ]
  },
  {
    mean: 0.9883297142528352,
    text: 'Rmb-denominated funds',
    box: [ [ 159, 241 ], [ 392, 241 ], [ 392, 261 ], [ 159, 261 ] ]
  },
  ... ...
]
```

这张识别手机截图的没事
```js
[
  {
    mean: 0.7437254358378668,
    text: '8:13:52 6 贴 5G 87%',
    box: [ [Array], [Array], [Array], [Array] ]
  },
  {
    mean: 0.9989335983991623,
    text: 'KB/S',
    box: [ [Array], [Array], [Array], [Array] ]
  },
  {
    mean: 0.9960503445731269,
    text: '请认真核对快递单号',
    box: [ [Array], [Array], [Array], [Array] ]
  },
  ... ...
]
```

### PR DESCRIPTION
**Pull request by gutenye**
Closes #22

### CODE REVIEW

File: packages/common/src/models/Recognition.ts [hunk 1]
```diff
@@ -137,77 +137,80 @@ function calculateBox({
...
+    totalHeight += height
+  }
+  return totalHeight / boxes.length
+}
 
-  for (const i of boxes) {
-    const t = []
-    let m = 0
-    for (const j of i) {
-      if(!ind.get(j)) continue;
```
Comment (gutenye) [inline packages/common/src/models/Recognition.ts:195]: Change this to `ind.get(j) === undefined` cause of number 0
